zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 01 Getting Started\01-HelloMsg\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 01 Getting Started\01-HelloMsg\HelloMsg.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 02 An Introduction to Unicode\01-ScrnSize\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 02 An Introduction to Unicode\01-ScrnSize\ScrnSize.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 03 Windows and Messages\01-HelloWin\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 03 Windows and Messages\01-HelloWin\HelloWin.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 04 An Exercise in Text Output\01 SysMets1\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 04 An Exercise in Text Output\01 SysMets1\SysMets.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 04 An Exercise in Text Output\01 SysMets1\SysMets1.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 04 An Exercise in Text Output\02 SysMets2\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 04 An Exercise in Text Output\02 SysMets2\SysMets2.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 04 An Exercise in Text Output\03 SysMets3\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 04 An Exercise in Text Output\03 SysMets3\SysMets3.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 05 Basic Drawing\01 DevCaps1\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 05 Basic Drawing\01 DevCaps1\DevCaps1.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 05 Basic Drawing\02-SineWave\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 05 Basic Drawing\02-SineWave\SineWave.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 05 Basic Drawing\03-LineDemo\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 05 Basic Drawing\03-LineDemo\LineDemo.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 05 Basic Drawing\04-Bezier\Bezier.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 05 Basic Drawing\04-Bezier\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 05 Basic Drawing\05-AltWind\AltWind.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 05 Basic Drawing\05-AltWind\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 05 Basic Drawing\06 WhatSize\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 05 Basic Drawing\06 WhatSize\WhatSize.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 05 Basic Drawing\07 RandRect\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 05 Basic Drawing\07 RandRect\RandRect.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 05 Basic Drawing\08 Clover\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 05 Basic Drawing\08 Clover\Clover.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 06 The Keyboard\01 SysMets4\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 06 The Keyboard\01 SysMets4\SysMets4.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 06 The Keyboard\02 KeyView1\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 06 The Keyboard\02 KeyView1\KeyView1.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 07 The Mouse\01-Connect\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 07 The Mouse\01-Connect\Connect.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 07 The Mouse\02-Checker1\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 07 The Mouse\02-Checker1\Checker1.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 07 The Mouse\03-Checker2\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 07 The Mouse\03-Checker2\Checker2.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 07 The Mouse\04-Checker3\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 07 The Mouse\04-Checker3\Checker3.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 07 The Mouse\05-Checker4\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 07 The Mouse\05-Checker4\Checker4.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 07 The Mouse\06-BlokOut1\BlokOut1.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 07 The Mouse\06-BlokOut1\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 07 The Mouse\07-BlokOut2\BlokOut2.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 07 The Mouse\07-BlokOut2\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 07 The Mouse\08-SysMets\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 07 The Mouse\08-SysMets\SysMets.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 08 The Timer\01-Beeper1\Beeper1.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 08 The Timer\01-Beeper1\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 08 The Timer\02-Beeper2\Beeper2.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\Chapter 08 The Timer\02-Beeper2\build.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\windowsx\windowsx.zig"
zig fmt "C:\Projects\petzold-pw5e-zig\windowsx\windowsx\windowsx.zig"
